name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH and Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 52.188.227.175 >> ~/.ssh/known_hosts
          ssh azureuser@52.188.227.175 << 'EOF'
            sudo pkill node || true
            cd /home/azureuser/backend-api || git clone <your-repo-url> backend-api && cd backend-api
            git pull origin main
            npm install
            sudo nohup node server.js > output.log 2>&1 &
          EOF
